### ISSUE TITLE
Markdown and Window Issues

### ISSUE THREAD

**Issue by bdielman** [lewisflude/Handcrafted#1]
First of all, love this theme! Great work! I did notice a couple of issue that I wanted to bring up:

When Panic's window doesn't have focus, the background color seems a bit off. Here's the comparison between the Handcrafted and Palette themes:

![Handcrafted Window](https://user-images.githubusercontent.com/94547/94051366-6ee2a600-fda5-11ea-8820-fc062337c05a.jpg)
![Palette Window](https://user-images.githubusercontent.com/94547/94051372-71450000-fda5-11ea-8aa9-e89706f50fb4.jpg)

When viewing code snippets in Markdown the contrast is off. Again, comparing Handcrafted with Palette:

![Handcrafted](https://user-images.githubusercontent.com/94547/94051485-96d20980-fda5-11ea-8292-829d989be82c.jpg)
![Palette](https://user-images.githubusercontent.com/94547/94051540-abae9d00-fda5-11ea-922e-d9fc0cf2dc6e.jpg)

**Comment by lewisflude** [comment]
@bdielman Thanks for bringing these issues to my attention! I've just pushed a release (1.5.3) that fixes both these issues. Now, an inactive titlebar will drop to a slightly darker tine, and the code snippet highlight will be a slightly lighter shade of the base colour.

Glad you're enjoying the theme! Any other issues, let me know and I'll be happy to put the work in to iron things out. :)

**Comment by bdielman** [comment]
Thanks for quick turnaround!

**Comment by lewisflude** [comment]
@bdielman no problem at all! I really appreciate you bringing up these issues. Hope all is looking good now.
